### ISSUE TITLE
Issue with minmax_scale (float) type error

### ISSUE THREAD

**Issue by galfaroi** [NawfalTachfine/PredictionAPI#1]
Hi
I have the following issue in the minmax scaler function:

TypeErrorTraceback (most recent call last)
<ipython-input-26-bdc020ca5329> in <module>()
----> 1 X = minmax_scale(X_tmp, BOUNDARIES)

<ipython-input-19-3a5271419cca> in minmax_scale(in_df, boundaries)
      5         col_name = '{}__norm'.format(feature)
      6 
----> 7         out_df[col_name] = round((out_df[feature] - min_val)/(max_val - min_val),3)
      8         out_df.loc[out_df[col_name] < 0, col_name] = 0
      9         out_df.loc[out_df[col_name] > 1, col_name] = 1

/home/german/miniconda2/lib/python2.7/site-packages/pandas/core/series.pyc in wrapper(self)
     95             return converter(self.iloc[0])
     96         raise TypeError("cannot convert the series to "
---> 97                         "{0}".format(str(converter)))
     98 
     99     return wrapper

TypeError: cannot convert the series to <type 'float'>

Even after I casted my dataframe as float and double check the following way: 

`X_tmp` = X_tmp.astype(float)

g = X_tmp.columns.to_series().groupby(X_tmp.dtypes).groups
g
{k.name: v for k, v in `g.items()}`

Any hints?

Thanks

**Comment by NawfalTachfine** [comment]
Hi German,

The code was written in Python3 and it seems that you're using Python2. Could you give it a try using a Python3 interpreter and let me know how that turns out?

**Comment by galfaroi** [comment]
Thank you, I will
